admin/urls.py
from django.urls import path
from . import views

app_name = "admin"

urlpatterns = [
    # path('',views.index, name="index"),
    path("request/", views.submit_admin_request, name="submit_admin_request"),
    path("manage/", views.manage_admin_requests, name="manage_admin_requests"),
    path("approve/<int:request_id>/", views.approve_request, name="approve_request"),
    path("reject/<int:request_id>/", views.reject_request, name="reject_request"),
]

devices/urls.py
from django.urls import path
from . import views

# Registering the devices namespace to be used in the ticket_app urls.py
app_name = "devices"

# Defining url patterns for the devices app
urlpatterns = [
    # Root pattern, displaying all devices
    path("", views.all_devices, name="all_devices"),
    # URL for the create_device page
    path("new/", views.create_device, name="create_device"),
    # URL for the edit device page, passed a primary key to identify what device to edit
    path("<int:pk>/edit/", views.edit_device, name="edit_device"),
    # URL for the delete device page, passed a primary key to identify what device to delete
    path("<int:pk>/delete/", views.delete_device, name="delete_device"),
]

ticket_app/urls.py
from django.urls import path, include


urlpatterns = [
    path("", include("users.urls", namespace="users")),
    path("tickets/", include("tickets.urls", namespace="tickets")),
    path("admin/", include("admin.urls", namespace="admin")),
    path("devices/", include("devices.urls", namespace="devices")),
]

tickets/urls.py
from django.urls import path
from . import views

# Registering the tickets namespace to be used in the ticket_app urls.py
app_name = "tickets"

urlpatterns = [
    # Root pattern displaying all tickets assigned to current user (admin) or raised by user (non admin)
    path("", views.ticket_list, name="ticket_list"),
    # URL for viewing all tickets
    path("all/", views.all_tickets, name="all_tickets"),
    # URL for created a new ticket
    path("new/", views.ticket_create, name="ticket_new"),
    # URL for viewing unassigned tickets
    path("unassigned/", views.unassigned_tickets, name="unassigned_tickets"),
    # URL to assign a ticket
    path("assign_ticket/", views.assign_ticket, name="assign_ticket"),
    # URL to edit a ticket
    path("<int:pk>/edit/", views.ticket_update, name="ticket_edit"),
    # URL to delete a ticket
    path("<int:pk>/delete/", views.ticket_delete, name="ticket_delete"),
    # URL to mark ticket as resolved
    path("<int:pk>/resolve/", views.resolve_ticket, name="resolve_ticket"),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "users"

urlpatterns = [
    # path('',views.index, name="index"),
    path("", views.landing_page, name="landing_page"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ticket Management System</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header>
        <div class="navbar">
            <div class="navbar-brand">TMS</div>
            {% if request.user.is_authenticated %}
                {% if request.user.is_staff %}
                    <a href="{% url 'tickets:ticket_list' %}" class="nav-item">My Tickets</a>
                    <a href="{% url 'tickets:unassigned_tickets' %}" class="nav-item">Unassigned Tickets</a>
                    <a href="{% url 'admin:manage_admin_requests' %}" class="nav-item">Manage Admin Requests</a>
                    <a href="{% url 'devices:all_devices' %}" class="nav-item">All Devices</a> 
                {% else %}
                    <a href="{% url 'tickets:ticket_list' %}" class="nav-item">My Tickets</a>
                    <a href="{% url 'tickets:ticket_new' %}" class="nav-item">Create Ticket</a>
                    <a href="{% url 'admin:submit_admin_request' %}" class="nav-item">Request Admin Account</a>
                {% endif %}
                    <a href="{% url 'tickets:all_tickets' %}" class="nav-item">All Tickets</a>
                    <form action="{% url 'users:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="nav-item">Logout</button>
                    </form>
            {% else %}
                <a href="{% url 'users:login' %}" class="nav-item">Login</a>
                <a href="{% url 'users:signup' %}" class="nav-item">Sign Up</a>
            {% endif %}
        </div>
    </header>

    <main>
        <script>
            function dismissMessage() {
                var messageBox = document.getElementById('message-box');
                if (messageBox) {
                    messageBox.style.display = 'none';
                }
            }
        </script>
        {% if messages %}
            <div id="message-box" style="position: fixed; top: 30; width: 100%; background-color: #f8d7da; color: #721c24; text-align: center; z-index: 1000;">
                {% for message in messages %}
                    <span>{{ message }}</span>
                    <button onclick="dismissMessage()" style="margin-left: 15px;">Dismiss</button>
                {% endfor %}
            </div>
        {% endif %}
        {% block content %}

        {% endblock %}
    </main>

    <footer>

    </footer>
</body>
</html>